apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: atlantis-route
spec:
  parentRefs:
    - name: system-gateway
      namespace: default
  hostnames:
    - atlantis.ninebasetwo.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: atlantis
          port: 80
