apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: trilium-route
spec:
  parentRefs:
    - name: apps-gateway
  hostnames:
    - trilium.ninebasetwo.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: trilium-svc
          port: 8080
