apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: system-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: argocd
      hostname: argocd.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: system-tls
            kind: Secret
    - name: alloy
      hostname: alloy.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: system-tls
            kind: Secret
    - name: grafana
      hostname: grafana.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: system-tls
            kind: Secret
    - name: ceph
      hostname: ceph.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: system-tls
            kind: Secret
    - name: atlantis
      hostname: atlantis.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: system-tls
            kind: Secret
