  apiVersion: gateway.networking.k8s.io/v1beta1
  kind: ReferenceGrant
  metadata:
    name: httproutes-to-gateway-ns-default
  spec:
    from:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        namespace: monitoring
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        namespace: argocd
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        namespace: atlantis
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        namespace: website
    to:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: system-gateway
