apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: website-route
spec:
  parentRefs:
    - name: default-gateway
      namespace: default
  hostnames:
    - ninebasetwo.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: website-svc
          port: 80
