apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: actual-route
spec:
  parentRefs:
    - name: apps-gateway
  hostnames:
    - actual.ninebasetwo.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: actual-budget-svc
          port: 5006
