apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ceph-route
spec:
  parentRefs:
    - name: default-gateway
      namespace: default
  hostnames:
    - ceph.ninebasetwo.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: rook-ceph-mgr-dashboard
          port: 8443
