apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: alloy-route
spec:
  parentRefs:
    - name: default-gateway
      namespace: default
  hostnames:
    - alloy.ninebasetwo.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: alloy
          port: 12345
