apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: default-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: website
      hostname: ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: default-gateway-tls
            kind: Secret
    - name: trilium
      hostname: trilium.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: default-gateway-tls
            kind: Secret
    - name: actual
      hostname: actual.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: default-gateway-tls
            kind: Secret
    - name: immich
      hostname: immich.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: default-gateway-tls
            kind: Secret
    - name: argocd
      hostname: argocd.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: default-gateway-tls
            kind: Secret
    - name: jellyfin
      hostname: jellyfin.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: default-gateway-tls
            kind: Secret
    - name: alloy
      hostname: alloy.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: default-gateway-tls
            kind: Secret
    - name: grafana
      hostname: grafana.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: default-gateway-tls
            kind: Secret
    - name: ceph
      hostname: ceph.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: default-gateway-tls
            kind: Secret
    - name: atlantis
      hostname: atlantis.ninebasetwo.net
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: default-gateway-tls
            kind: Secret
