  apiVersion: gateway.networking.k8s.io/v1beta1
  kind: ReferenceGrant
  metadata:
    name: httproutes-to-gateway-ns-default
  spec:
    from:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        namespace: actual-budget
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        namespace: immich
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        namespace: trilium-notes
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        namespace: website
    to:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: apps-gateway  # ← Gateway autorisé
